GET http://localhost:3000
###
GET http://localhost:3000/books

###
GET http://localhost:3000/books/609a8f89d26c33966a76676d
###
POST http://localhost:3000/books
content-Type: application/json

{
    "title":"Le nerf vague",
    "description":"Comment activer le mode Parasympathique",
    "price":22,
    "auteur":"Stephan Porges",
    "stars":5

}
###
PATCH http://localhost:3000/books/609a8f89d26c33966a76676d
content-Type:application/json
{
    // mettre ici le champ du livre a mettre a jour
}
###
DELETE http://localhost:3000/books/609a8f89d26c33966a76676d
Content-Type: application/json
{

}

